---
title: "UCLA Logit TEST"
author: "mcc"
date: "12/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(aod)
library(ggplot2)
```

```{r}
mydata <- read.csv("https://stats.idre.ucla.edu/stat/data/binary.csv")
## view the first few rows of the data
head(mydata)
```


```{r}
summary(mydata)
```

```{r}
sapply(mydata, sd)
```

```{r}
## two-way contingency table of categorical outcome and predictors we want
## to make sure there are not 0 cells
xtabs(~admit + rank, data = mydata)
```


```{r}
mydata$rank <- factor(mydata$rank)
mylogit <- glm(admit ~ gre + gpa + rank, data = mydata, family = "binomial")

summary(mylogit)
```


```{r}
## CIs using profiled log-likelihood
confint(mylogit)
```

```{r}
## CIs using standard errors
confint.default(mylogit)
```


```{r}
wald.test(b = coef(mylogit), Sigma = vcov(mylogit), Terms = 4:6)

```



```{r}
## odds ratios only
exp(coef(mylogit))
```

```{r}
## odds ratios and 95% CI
exp(cbind(OR = coef(mylogit), confint(mylogit)))
```

```{r}
newdata1 <- with(mydata, data.frame(gre = mean(gre), gpa = mean(gpa), rank = factor(1:4)))

## view data frame
newdata1
```


```{r}
newdata1$rankP <- predict(mylogit, newdata = newdata1, type = "response")
newdata1
```


```{r}
newdata2 <- with(mydata, data.frame(gre = rep(seq(from = 200, to = 800, length.out = 100), 4), 
                                    gpa = mean(gpa), 
                                    rank = factor(rep(1:4, each = 100))))
```


```{r}
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link",
    se = TRUE))
newdata3 <- within(newdata3, {
    PredictedProb <- plogis(fit)
    LL <- plogis(fit - (1.96 * se.fit))
    UL <- plogis(fit + (1.96 * se.fit))
})

## view first few rows of final dataset
head(newdata3)
```


```{r}
ggplot(newdata3, 
       aes(x = gre, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = rank), alpha = 0.2) + 
  geom_line(aes(colour = rank), size = 1)
```






















